<?php
$errorLogMessage = [
    1 => 'Veuillez entrer votre nom',
    2 => 'Veuillez entrer votre prénom',
    3 => 'Veuillez entrer votre date de naissance',
    4 => 'Veuillez entrer votre adresse',
    5 => 'Veuillez entrer votre email',
    6 => 'Veuillez entrer votre pays',
    7 => 'Veuillez entrer votre pays de naissance',
    8 => 'Veuillez entrer votre numéro de téléphone',
    9 => 'Veuillez entrer votre numéro pole emploi',
    10 => 'Veuillez entrer votre nombre de badge',
    11 => 'Veuillez entrer votre lien Codecademy',
    12 => 'Veuillez répondre à la question',
    13 => 'Veuillez répondre à la question',
    14 => 'Veuillez répondre à la question',
    15 => 'Veuillez saisir votre niveau scolaire',
    201 => 'Veuillez entrer un nom valide',
    202 => 'Veuillez entrer un prénom valide',
    203 => 'Veuillez entrer une date de naissance valide',
    204 => 'Veuillez entrer une adresse valide',
    205 => 'Veuillez entrer un email valide',
    206 => 'Veuillez entrer un pays valide',
    207 => 'Veuillez entrer un pays de naissance valide',
    208 => 'Veuillez entrer un numéro de téléphone valide',
    209 => 'Veuillez entrer un numéro pole emploi valide',
    210 => 'Veuillez entrer un nombre de badge valide',
    211 => 'Veuillez entrer un lien Codecademy valide',
    212 => 'Veuillez répondre à la question correctement',
    213 => 'Veuillez répondre à la question correctement',
    214 => 'Veuillez répondre à la question correctement',
    215 => 'Veuillez saisir un niveau scolaire valide',
    ];
?>

